name: release

on:
  push:
    branches:
      - "master"
    tags:
      - "*"  # 匹配所有的 tag 推送
permissions:
  contents: write  # 必须允许对内容的写权限，这样才能发布 release 和上传文件

jobs:
  releases-linux-binaries:
    name: Release Go Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.51
        with:
          github_token: ${{ secrets.LGITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 1.17